// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/csv-ui/Engineering.tsx": () => import("../components/mockups/csv-ui/Engineering.tsx"),
  "./components/mockups/csv-ui/SaaS.tsx": () => import("../components/mockups/csv-ui/SaaS.tsx"),
  "./components/mockups/csv-ui/Workflow.tsx": () => import("../components/mockups/csv-ui/Workflow.tsx")
};
